### ISSUE TITLE
compilation error on master: irrefutable pattern (Windows only)

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#89]
**Describe the bug**

commit `38e3dcb98c60a239064653cc002f5c458b3eab67` does not compile with rustc `1.31.0` (`abe02cefd` 2018-12-04).

```
error[E0162]: irrefutable if-let pattern
  --> src\network\grpc\bootstrap.rs:95:16
   |
95 |         if let Connection::Tcp(addr) = self.connection {
   |                ^^^^^^^^^^^^^^^^^^^^^ irrefutable pattern
```

**To Reproduce**

1. checkout the commit;
2. make sure cardano-deps is at the right commit too;
3. `cargo build`

**Expected behavior**

to compile without errors

**Additional context**

rust toolchain used here: `stable-x86_64-pc-windows-msvc`
